In [1]:
import pandas as pd

In [2]:
df_2022 = pd.read_csv('mulheres-dados-2022.csv')
df_2022

,"('P0', 'id')","('P1_a ', 'Idade')","('P1_a_1 ', 'Faixa idade')","('P1_b ', 'Genero')","('P1_c ', 'Cor/raca/etnia')","('P1_d ', 'PCD')","('P1_e ', 'experiencia_profissional_prejudicada')","('P1_f ', 'aspectos_prejudicados')","('P1_g ', 'vive_no_brasil')","('P1_i ', 'Estado onde mora')",...,"('P8_d_2 ', 'Coletando e limpando os dados que uso para análise e modelagem.')","('P8_d_3 ', 'Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.')","('P8_d_4 ', 'Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).')","('P8_d_5 ', 'Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.')","('P8_d_6 ', 'Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.')","('P8_d_7 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.')","('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')","('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')","('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')","('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')"
0,zzqzz3l9ily8nuo2m7wyzzqzz3w48o96,39.0,35-39,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,NaN,True,Distrito Federal (DF),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,zzls2oftfn9law393oezzls2ofhvfpzd,32.0,30-34,Masculino,Parda,Não,"Sim, acredito que a minha a experiência profis...",Aprovação em processos seletivos/entrevistas,True,Pará (PA),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,zzdwqzfqqp1ypc7ps6m0hzzdwqz292yi,53.0,50-54,Masculino,Branca,Não,NaN,NaN,True,Distrito Federal (DF),...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,zzbqh3uy7yk7k9qmkzzbqtb4s9faqspl,27.0,25-29,Masculino,Branca,Não,NaN,NaN,True,Minas Gerais (MG),...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,zzaf1m95yan929rb94wzzaf1mekhvhpg,46.0,45-49,Feminino,Branca,Não,Não acredito que minha experiência profissiona...,NaN,True,Pará (PA),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4266,01jnrn9f6va0menfhk2ztm01jnrn96bp,26.0,25-29,Masculino,Branca,Não,NaN,NaN,True,São Paulo (SP),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4267,01dyfxam4u4bi29fem01dyfxaq9akvqp,30.0,30-34,Feminino,Branca,Não,Não acredito que minha experiência profissiona...,NaN,True,Minas Gerais (MG),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4268,00zw9ks9d40z4u00zz3d20iix65qpli3,29.0,25-29,Masculino,Branca,Não,NaN,NaN,True,São Paulo (SP),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4269,00xu7yujd7s57emj00xu7y0c3njix3de,NaN,17-21,Masculino,Branca,Não,NaN,NaN,True,São Paulo (SP),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4270,00lb35llmdsidpa00lb35qcdysnzvhv7,24.0,22-24,Masculino,Branca,Não,NaN,NaN,True,Goiás (GO),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_2022.columns

Index(['('P0', 'id')', '('P1_a ', 'Idade')', '('P1_a_1 ', 'Faixa idade')',
       '('P1_b ', 'Genero')', '('P1_c ', 'Cor/raca/etnia')',
       '('P1_d ', 'PCD')', '('P1_e ', 'experiencia_profissional_prejudicada')',
       '('P1_f ', 'aspectos_prejudicados')', '('P1_g ', 'vive_no_brasil')',
       '('P1_i ', 'Estado onde mora')',
       ...
       '('P8_d_2 ', 'Coletando e limpando os dados que uso para análise e modelagem.')',
       '('P8_d_3 ', 'Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.')',
       '('P8_d_4 ', 'Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).')',
       '('P8_d_5 ', 'Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.')',
       '('P8_d_6 ', 'Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.')',
       '('P8_d_7 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.')',
       '('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')',
       '('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')',
       '('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')',
       '('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')'],
      dtype='object', length=353)

In [5]:
colunas = df_2022.loc[:, ["('P0', 'id')",
"('P1_a_1 ', 'Faixa idade')",
"('P1_b ', 'Genero')",
"('P1_c ', 'Cor/raca/etnia')",
"('P1_d ', 'PCD')",
"('P2_h ', 'Faixa salarial')",
"('P2_l_2 ', 'Salário atual não corresponde ao mercado')",
"('P1_l ', 'Nivel de Ensino')","('P1_m ', 'Área de Formação')",
"('P2_a ', 'Qual sua situação atual de trabalho?')",
"('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')",
"('P5_c ', 'Há quanto tempo você busca uma oportunidade na área de dados?')","('P5_d ', 'Como tem sido a busca por um emprego na área de dados?')",
"('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')","('P2_o_1 ', 'Remuneração/Salário')",
"('P2_p ', 'Atualmente qual a sua forma de trabalho?')"
]]

In [6]:
colunas

,"('P0', 'id')","('P1_a_1 ', 'Faixa idade')","('P1_b ', 'Genero')","('P1_c ', 'Cor/raca/etnia')","('P1_d ', 'PCD')","('P2_h ', 'Faixa salarial')","('P2_l_2 ', 'Salário atual não corresponde ao mercado')","('P1_l ', 'Nivel de Ensino')","('P1_m ', 'Área de Formação')","('P2_a ', 'Qual sua situação atual de trabalho?')","('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')","('P5_c ', 'Há quanto tempo você busca uma oportunidade na área de dados?')","('P5_d ', 'Como tem sido a busca por um emprego na área de dados?')","('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')","('P2_o_1 ', 'Remuneração/Salário')","('P2_p ', 'Atualmente qual a sua forma de trabalho?')"
0,zzqzz3l9ily8nuo2m7wyzzqzz3w48o96,35-39,Masculino,Parda,Não,de R$ 8.001/mês a R$ 12.000/mês,NaN,Pós-graduação,Computação / Engenharia de Software / Sistemas...,Servidor Público,Não participei de entrevistas de emprego/proce...,NaN,NaN,Benefícios,0.0,Modelo 100% presencial
1,zzls2oftfn9law393oezzls2ofhvfpzd,30-34,Masculino,Parda,Não,de R$ 4.001/mês a R$ 6.000/mês,0.0,Graduação/Bacharelado,Outras Engenharias,Empregado (CLT),"Sim, fiz entrevistas mas não fui aprovado",NaN,NaN,"Remuneração/Salário, Plano de carreira e oport...",1.0,Modelo 100% presencial
2,zzdwqzfqqp1ypc7ps6m0hzzdwqz292yi,50-54,Masculino,Branca,Não,de R$ 12.001/mês a R$ 16.000/mês,0.0,Pós-graduação,Computação / Engenharia de Software / Sistemas...,Empregado (CLT),Não participei de entrevistas de emprego/proce...,NaN,NaN,"Remuneração/Salário, Flexibilidade de trabalho...",1.0,Modelo híbrido com dias fixos de trabalho pres...
3,zzbqh3uy7yk7k9qmkzzbqtb4s9faqspl,25-29,Masculino,Branca,Não,de R$ 12.001/mês a R$ 16.000/mês,NaN,Doutorado ou Phd,Estatística/ Matemática / Matemática Computaci...,Empregado (CLT),"Sim, fui aprovado e mudei de emprego",NaN,NaN,"Remuneração/Salário, Flexibilidade de trabalho...",1.0,Modelo híbrido flexível (o funcionário tem lib...
4,zzaf1m95yan929rb94wzzaf1mekhvhpg,45-49,Feminino,Branca,Não,de R$ 6.001/mês a R$ 8.000/mês,0.0,Pós-graduação,Computação / Engenharia de Software / Sistemas...,Servidor Público,Não participei de entrevistas de emprego/proce...,NaN,NaN,"Remuneração/Salário, Oportunidade de aprendiza...",1.0,Modelo 100% presencial
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4266,01jnrn9f6va0menfhk2ztm01jnrn96bp,25-29,Masculino,Branca,Não,de R$ 4.001/mês a R$ 6.000/mês,NaN,Graduação/Bacharelado,Computação / Engenharia de Software / Sistemas...,Empregado (CLT),"Sim, fui aprovado e mudei de emprego",NaN,NaN,"Remuneração/Salário, Benefícios, Flexibilidade...",1.0,Modelo 100% remoto
4267,01dyfxam4u4bi29fem01dyfxaq9akvqp,30-34,Feminino,Branca,Não,de R$ 3.001/mês a R$ 4.000/mês,NaN,Mestrado,Outras Engenharias,Empregado (CLT),Não participei de entrevistas de emprego/proce...,NaN,NaN,"Ambiente e clima de trabalho, Plano de carreir...",0.0,Modelo 100% remoto
4268,00zw9ks9d40z4u00zz3d20iix65qpli3,25-29,Masculino,Branca,Não,de R$ 16.001/mês a R$ 20.000/mês,NaN,Mestrado,Outras Engenharias,Empreendedor ou Empregado (CNPJ),"Sim, fui aprovado mas decidi não mudar de emprego",NaN,NaN,"Remuneração/Salário, Ambiente e clima de traba...",1.0,Modelo híbrido com dias fixos de trabalho pres...
4269,00xu7yujd7s57emj00xu7y0c3njix3de,17-21,Masculino,Branca,Não,Menos de R$ 1.000/mês,NaN,Não tenho graduação formal,NaN,Estagiário,Não participei de entrevistas de emprego/proce...,NaN,NaN,Oportunidade de aprendizado e trabalhar com re...,1.0,Modelo 100% presencial
4270,00lb35llmdsidpa00lb35qcdysnzvhv7,22-24,Masculino,Branca,Não,de R$ 3.001/mês a R$ 4.000/mês,1.0,Graduação/Bacharelado,Computação / Engenharia de Software / Sistemas...,Empregado (CLT),"Sim, fiz entrevistas mas não fui aprovado",NaN,NaN,"Remuneração/Salário, Oportunidade de aprendiza...",1.0,Modelo 100% remoto

In [7]:
colunas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4271 entries, 0 to 4270
Data columns (total 16 columns):
 #   Column                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                          --------------  -----
 0   ('P0', 'id')                                                                                                    4271 non-null   object
 1   ('P1_a_1 ', 'Faixa idade')                                                                                      4271 non-null   object
 2   ('P1_b ', 'Genero')                                                                                             4262 non-null   object
 3   ('P1_c ', 'Cor/raca/etnia')                                                                                     4271 non-null   object
 4   ('P1_d ', 'PCD')                                                                                                4271 non-null   object
 5   ('P2_h ', 'Faixa salarial')                                                                                     3694 non-null   object
 6   ('P2_l_2 ', 'Salário atual não corresponde ao mercado')                                                         960 non-null    float64
 7   ('P1_l ', 'Nivel de Ensino')                                                                                    4271 non-null   object
 8   ('P1_m ', 'Área de Formação')                                                                                   4149 non-null   object
 9   ('P2_a ', 'Qual sua situação atual de trabalho?')                                                               4271 non-null   object
 10  ('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')                                     3694 non-null   object
 11  ('P5_c ', 'Há quanto tempo você busca uma oportunidade na área de dados?')                                      343 non-null    object
 12  ('P5_d ', 'Como tem sido a busca por um emprego na área de dados?')                                             344 non-null    object
 13  ('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')  3694 non-null   object
 14  ('P2_o_1 ', 'Remuneração/Salário')                                                                              3694 non-null   float64
 15  ('P2_p ', 'Atualmente qual a sua forma de trabalho?')                                                           3694 non-null   object
dtypes: float64(2), object(14)
memory usage: 534.0+ KB

In [8]:
colunas.isnull().sum()

('P0', 'id')                                                                                                         0
('P1_a_1 ', 'Faixa idade')                                                                                           0
('P1_b ', 'Genero')                                                                                                  9
('P1_c ', 'Cor/raca/etnia')                                                                                          0
('P1_d ', 'PCD')                                                                                                     0
('P2_h ', 'Faixa salarial')                                                                                        577
('P2_l_2 ', 'Salário atual não corresponde ao mercado')                                                           3311
('P1_l ', 'Nivel de Ensino')                                                                                         0
('P1_m ', 'Área de Formação')                                                                                      122
('P2_a ', 'Qual sua situação atual de trabalho?')                                                                    0
('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')                                        577
('P5_c ', 'Há quanto tempo você busca uma oportunidade na área de dados?')                                        3928
('P5_d ', 'Como tem sido a busca por um emprego na área de dados?')                                               3927
('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')     577
('P2_o_1 ', 'Remuneração/Salário')                                                                                 577
('P2_p ', 'Atualmente qual a sua forma de trabalho?')                                                              577
dtype: int64

In [9]:
deletar_colunas = ["('P2_l_2 ', 'Salário atual não corresponde ao mercado')", 
    "('P5_c ', 'Há quanto tempo você busca uma oportunidade na área de dados?')", 
    "('P5_d ', 'Como tem sido a busca por um emprego na área de dados?')"
]

In [10]:
colunas = colunas.drop(deletar_colunas, axis=1)
colunas

,"('P0', 'id')","('P1_a_1 ', 'Faixa idade')","('P1_b ', 'Genero')","('P1_c ', 'Cor/raca/etnia')","('P1_d ', 'PCD')","('P2_h ', 'Faixa salarial')","('P1_l ', 'Nivel de Ensino')","('P1_m ', 'Área de Formação')","('P2_a ', 'Qual sua situação atual de trabalho?')","('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')","('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')","('P2_o_1 ', 'Remuneração/Salário')","('P2_p ', 'Atualmente qual a sua forma de trabalho?')"
0,zzqzz3l9ily8nuo2m7wyzzqzz3w48o96,35-39,Masculino,Parda,Não,de R$ 8.001/mês a R$ 12.000/mês,Pós-graduação,Computação / Engenharia de Software / Sistemas...,Servidor Público,Não participei de entrevistas de emprego/proce...,Benefícios,0.0,Modelo 100% presencial
1,zzls2oftfn9law393oezzls2ofhvfpzd,30-34,Masculino,Parda,Não,de R$ 4.001/mês a R$ 6.000/mês,Graduação/Bacharelado,Outras Engenharias,Empregado (CLT),"Sim, fiz entrevistas mas não fui aprovado","Remuneração/Salário, Plano de carreira e oport...",1.0,Modelo 100% presencial
2,zzdwqzfqqp1ypc7ps6m0hzzdwqz292yi,50-54,Masculino,Branca,Não,de R$ 12.001/mês a R$ 16.000/mês,Pós-graduação,Computação / Engenharia de Software / Sistemas...,Empregado (CLT),Não participei de entrevistas de emprego/proce...,"Remuneração/Salário, Flexibilidade de trabalho...",1.0,Modelo híbrido com dias fixos de trabalho pres...
3,zzbqh3uy7yk7k9qmkzzbqtb4s9faqspl,25-29,Masculino,Branca,Não,de R$ 12.001/mês a R$ 16.000/mês,Doutorado ou Phd,Estatística/ Matemática / Matemática Computaci...,Empregado (CLT),"Sim, fui aprovado e mudei de emprego","Remuneração/Salário, Flexibilidade de trabalho...",1.0,Modelo híbrido flexível (o funcionário tem lib...
4,zzaf1m95yan929rb94wzzaf1mekhvhpg,45-49,Feminino,Branca,Não,de R$ 6.001/mês a R$ 8.000/mês,Pós-graduação,Computação / Engenharia de Software / Sistemas...,Servidor Público,Não participei de entrevistas de emprego/proce...,"Remuneração/Salário, Oportunidade de aprendiza...",1.0,Modelo 100% presencial
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4266,01jnrn9f6va0menfhk2ztm01jnrn96bp,25-29,Masculino,Branca,Não,de R$ 4.001/mês a R$ 6.000/mês,Graduação/Bacharelado,Computação / Engenharia de Software / Sistemas...,Empregado (CLT),"Sim, fui aprovado e mudei de emprego","Remuneração/Salário, Benefícios, Flexibilidade...",1.0,Modelo 100% remoto
4267,01dyfxam4u4bi29fem01dyfxaq9akvqp,30-34,Feminino,Branca,Não,de R$ 3.001/mês a R$ 4.000/mês,Mestrado,Outras Engenharias,Empregado (CLT),Não participei de entrevistas de emprego/proce...,"Ambiente e clima de trabalho, Plano de carreir...",0.0,Modelo 100% remoto
4268,00zw9ks9d40z4u00zz3d20iix65qpli3,25-29,Masculino,Branca,Não,de R$ 16.001/mês a R$ 20.000/mês,Mestrado,Outras Engenharias,Empreendedor ou Empregado (CNPJ),"Sim, fui aprovado mas decidi não mudar de emprego","Remuneração/Salário, Ambiente e clima de traba...",1.0,Modelo híbrido com dias fixos de trabalho pres...
4269,00xu7yujd7s57emj00xu7y0c3njix3de,17-21,Masculino,Branca,Não,Menos de R$ 1.000/mês,Não tenho graduação formal,NaN,Estagiário,Não participei de entrevistas de emprego/proce...,Oportunidade de aprendizado e trabalhar com re...,1.0,Modelo 100% presencial
4270,00lb35llmdsidpa00lb35qcdysnzvhv7,22-24,Masculino,Branca,Não,de R$ 3.001/mês a R$ 4.000/mês,Graduação/Bacharelado,Computação / Engenharia de Software / Sistemas...,Empregado (CLT),"Sim, fiz entrevistas mas não fui aprovado","Remuneração/Salário, Oportunidade de aprendiza...",1.0,Modelo 100% remoto

In [11]:
colunas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4271 entries, 0 to 4270
Data columns (total 13 columns):
 #   Column                                                                                                          Non-Null Count  Dtype
---  ------                                                                                                          --------------  -----
 0   ('P0', 'id')                                                                                                    4271 non-null   object
 1   ('P1_a_1 ', 'Faixa idade')                                                                                      4271 non-null   object
 2   ('P1_b ', 'Genero')                                                                                             4262 non-null   object
 3   ('P1_c ', 'Cor/raca/etnia')                                                                                     4271 non-null   object
 4   ('P1_d ', 'PCD')                                                                                                4271 non-null   object
 5   ('P2_h ', 'Faixa salarial')                                                                                     3694 non-null   object
 6   ('P1_l ', 'Nivel de Ensino')                                                                                    4271 non-null   object
 7   ('P1_m ', 'Área de Formação')                                                                                   4149 non-null   object
 8   ('P2_a ', 'Qual sua situação atual de trabalho?')                                                               4271 non-null   object
 9   ('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')                                     3694 non-null   object
 10  ('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')  3694 non-null   object
 11  ('P2_o_1 ', 'Remuneração/Salário')                                                                              3694 non-null   float64
 12  ('P2_p ', 'Atualmente qual a sua forma de trabalho?')                                                           3694 non-null   object
dtypes: float64(1), object(12)
memory usage: 433.9+ KB

In [12]:
df_mulheres_2022 = colunas
df_mulheres_2022

,"('P0', 'id')","('P1_a_1 ', 'Faixa idade')","('P1_b ', 'Genero')","('P1_c ', 'Cor/raca/etnia')","('P1_d ', 'PCD')","('P2_h ', 'Faixa salarial')","('P1_l ', 'Nivel de Ensino')","('P1_m ', 'Área de Formação')","('P2_a ', 'Qual sua situação atual de trabalho?')","('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')","('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')","('P2_o_1 ', 'Remuneração/Salário')","('P2_p ', 'Atualmente qual a sua forma de trabalho?')"
0,zzqzz3l9ily8nuo2m7wyzzqzz3w48o96,35-39,Masculino,Parda,Não,de R$ 8.001/mês a R$ 12.000/mês,Pós-graduação,Computação / Engenharia de Software / Sistemas...,Servidor Público,Não participei de entrevistas de emprego/proce...,Benefícios,0.0,Modelo 100% presencial
1,zzls2oftfn9law393oezzls2ofhvfpzd,30-34,Masculino,Parda,Não,de R$ 4.001/mês a R$ 6.000/mês,Graduação/Bacharelado,Outras Engenharias,Empregado (CLT),"Sim, fiz entrevistas mas não fui aprovado","Remuneração/Salário, Plano de carreira e oport...",1.0,Modelo 100% presencial
2,zzdwqzfqqp1ypc7ps6m0hzzdwqz292yi,50-54,Masculino,Branca,Não,de R$ 12.001/mês a R$ 16.000/mês,Pós-graduação,Computação / Engenharia de Software / Sistemas...,Empregado (CLT),Não participei de entrevistas de emprego/proce...,"Remuneração/Salário, Flexibilidade de trabalho...",1.0,Modelo híbrido com dias fixos de trabalho pres...
3,zzbqh3uy7yk7k9qmkzzbqtb4s9faqspl,25-29,Masculino,Branca,Não,de R$ 12.001/mês a R$ 16.000/mês,Doutorado ou Phd,Estatística/ Matemática / Matemática Computaci...,Empregado (CLT),"Sim, fui aprovado e mudei de emprego","Remuneração/Salário, Flexibilidade de trabalho...",1.0,Modelo híbrido flexível (o funcionário tem lib...
4,zzaf1m95yan929rb94wzzaf1mekhvhpg,45-49,Feminino,Branca,Não,de R$ 6.001/mês a R$ 8.000/mês,Pós-graduação,Computação / Engenharia de Software / Sistemas...,Servidor Público,Não participei de entrevistas de emprego/proce...,"Remuneração/Salário, Oportunidade de aprendiza...",1.0,Modelo 100% presencial
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4266,01jnrn9f6va0menfhk2ztm01jnrn96bp,25-29,Masculino,Branca,Não,de R$ 4.001/mês a R$ 6.000/mês,Graduação/Bacharelado,Computação / Engenharia de Software / Sistemas...,Empregado (CLT),"Sim, fui aprovado e mudei de emprego","Remuneração/Salário, Benefícios, Flexibilidade...",1.0,Modelo 100% remoto
4267,01dyfxam4u4bi29fem01dyfxaq9akvqp,30-34,Feminino,Branca,Não,de R$ 3.001/mês a R$ 4.000/mês,Mestrado,Outras Engenharias,Empregado (CLT),Não participei de entrevistas de emprego/proce...,"Ambiente e clima de trabalho, Plano de carreir...",0.0,Modelo 100% remoto
4268,00zw9ks9d40z4u00zz3d20iix65qpli3,25-29,Masculino,Branca,Não,de R$ 16.001/mês a R$ 20.000/mês,Mestrado,Outras Engenharias,Empreendedor ou Empregado (CNPJ),"Sim, fui aprovado mas decidi não mudar de emprego","Remuneração/Salário, Ambiente e clima de traba...",1.0,Modelo híbrido com dias fixos de trabalho pres...
4269,00xu7yujd7s57emj00xu7y0c3njix3de,17-21,Masculino,Branca,Não,Menos de R$ 1.000/mês,Não tenho graduação formal,NaN,Estagiário,Não participei de entrevistas de emprego/proce...,Oportunidade de aprendizado e trabalhar com re...,1.0,Modelo 100% presencial
4270,00lb35llmdsidpa00lb35qcdysnzvhv7,22-24,Masculino,Branca,Não,de R$ 3.001/mês a R$ 4.000/mês,Graduação/Bacharelado,Computação / Engenharia de Software / Sistemas...,Empregado (CLT),"Sim, fiz entrevistas mas não fui aprovado","Remuneração/Salário, Oportunidade de aprendiza...",1.0,Modelo 100% remoto

In [13]:
df_2023 = pd.read_csv('mulheres-dados-2023.csv')
df_2023

,"('P0', 'id')","('P1_a ', 'Idade')","('P1_a_1 ', 'Faixa idade')","('P1_b ', 'Genero')","('P1_c ', 'Cor/raca/etnia')","('P1_d ', 'PCD')","('P1_e ', 'experiencia_profissional_prejudicada')","('P1_e_1 ', 'Não acredito que minha experiência profissional seja afetada')","('P1_e_2 ', 'Experiencia prejudicada devido a minha Cor Raça Etnia')","('P1_e_3 ', 'Experiencia prejudicada devido a minha identidade de gênero')",...,"('P8_d_3 ', 'Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.')","('P8_d_4 ', 'Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).')","('P8_d_5 ', 'Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.')","('P8_d_6 ', 'Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.')","('P8_d_7 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.')","('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')","('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')","('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')","('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')","('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')"
0,001b2d1qtli8t9z7oqgdhj001b2d4i0g,31,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0026aa3fwd78u0026asg7456tfkjg2cs,30,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00r21rb9pusd1b0v7ew00r21rw3dy69w,37,35-39,Feminino,Amarela,Não,"Sim, acredito que a minha a experiência profis...",0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,00urm3jf2cek12w6ygue00urm3jzd17j,22,22-24,Masculino,Preta,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00v0az4g792svil00vn6y1kfm9hq8vy9,34,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5288,zyg9519671iqrgy93qzyg95183k8ix5f,34,30-34,Masculino,Preta,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5289,zyppgxzxko25qkgwsbrgpzyppgxzxs81,32,30-34,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5290,zysl5f50cnz3r0cbe6t2zysrxbzfsrng,25,25-29,Masculino,Branca,Não,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5291,zyt2656c9e1becxp457zyt26566dsng8,31,30-34,Masculino,Parda,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5292,zzvyz3z5jy2lzzvyziv62lvtjrab9r5x,31,30-34,Masculino,Amarela,Não,Não acredito que minha experiência profissiona...,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_colunas2 = df_2023[["('P0', 'id')",
"('P1_a_1 ', 'Faixa idade')",
"('P1_b ', 'Genero')",
"('P1_c ', 'Cor/raca/etnia')",
"('P1_d ', 'PCD')",
"('P2_h ', 'Faixa salarial')",
"('P1_l ', 'Nivel de Ensino')","('P1_m ', 'Área de Formação')",
"('P2_a ', 'Qual sua situação atual de trabalho?')",
"('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')",
"('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')",
"('P2_o_1 ', 'Remuneração/Salário')",
"('P2_r ', 'Atualmente qual a sua forma de trabalho?')"
]]

In [21]:
df_2023.columns

Index(['('P0', 'id')', '('P1_a ', 'Idade')', '('P1_a_1 ', 'Faixa idade')',
       '('P1_b ', 'Genero')', '('P1_c ', 'Cor/raca/etnia')',
       '('P1_d ', 'PCD')', '('P1_e ', 'experiencia_profissional_prejudicada')',
       '('P1_e_1 ', 'Não acredito que minha experiência profissional seja afetada')',
       '('P1_e_2 ', 'Experiencia prejudicada devido a minha Cor Raça Etnia')',
       '('P1_e_3 ', 'Experiencia prejudicada devido a minha identidade de gênero')',
       ...
       '('P8_d_3 ', 'Entrando em contato com os times de negócio para definição do problema, identificar a solução e apresentação de resultados.')',
       '('P8_d_4 ', 'Desenvolvendo modelos de Machine Learning com o objetivo de colocar em produção em sistemas (produtos de dados).')',
       '('P8_d_5 ', 'Colocando modelos em produção, criando os pipelines de dados, APIs de consumo e monitoramento.')',
       '('P8_d_6 ', 'Cuidando da manutenção de modelos de Machine Learning já em produção, atuando no monitoramento, ajustes e refatoração quando necessário.')',
       '('P8_d_7 ', 'Realizando construções de dashboards em ferramentas de BI como PowerBI, Tableau, Looker, Qlik, etc.')',
       '('P8_d_8 ', 'Utilizando ferramentas avançadas de estatística como SAS, SPSS, Stata etc, para realizar análises.')',
       '('P8_d_9 ', 'Criando e dando manutenção em ETLs, DAGs e automações de pipelines de dados.')',
       '('P8_d_10 ', 'Criando e gerenciando soluções de Feature Store e cultura de MLOps.')',
       '('P8_d_11 ', 'Criando e mantendo a infra que meus modelos e soluções rodam (clusters, servidores, API, containers, etc.)')',
       '('P8_d_12 ', 'Treinando e aplicando LLM's para solucionar problemas de negócio.')'],
      dtype='object', length=399)

In [22]:
df_colunas2.isnull().sum()

('P0', 'id')                                                                                                        0
('P1_a_1 ', 'Faixa idade')                                                                                          0
('P1_b ', 'Genero')                                                                                                 0
('P1_c ', 'Cor/raca/etnia')                                                                                         0
('P1_d ', 'PCD')                                                                                                    0
('P2_h ', 'Faixa salarial')                                                                                       540
('P1_l ', 'Nivel de Ensino')                                                                                        0
('P1_m ', 'Área de Formação')                                                                                     113
('P2_a ', 'Qual sua situação atual de trabalho?')                                                                   0
('P2_m ', 'Você participou de entrevistas de emprego nos últimos 6 meses?')                                       540
('P2_o ', 'Quais os principais critérios que você leva em consideração no momento de decidir onde trabalhar?')    566
('P2_o_1 ', 'Remuneração/Salário')                                                                                566
('P2_r ', 'Atualmente qual a sua forma de trabalho?')                                                             540
dtype: int64

In [29]:
df_mulheres_2022.rename(columns={"(\'P1_b \', \'Genero\')": "genero"},inplace = True)